import { AudioPlayer } from './audioPlayer.js';
import { AudioAnalyzer } from './eq.js';
import { supabase } from './supabaseClient.js';

const player = new AudioPlayer();
const analyzer = new AudioAnalyzer(player.audio);
let playlist = [], currentIndex = 0, shuffle = false, authUser = null;
const $ = id => document.getElementById(id);
const rooms = ['collection','list','equalizer','transmission','profile'];
const nav = [...document.querySelectorAll('.nav-tab')];
const wheel = $('song-wheel'), selector = $('song-selector');
const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt = s => Number.isFinite(s) ? `${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}` : '00:00';
const cover = s => s?.cover_path ? supabase.storage.from('covers').getPublicUrl(s.cover_path).data.publicUrl : 'assets/default-art.jpg';
const audio = s => s?.audio_path ? supabase.storage.from('audio').getPublicUrl(s.audio_path).data.publicUrl : '';
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2500)}
function room(n){rooms.forEach(r=>$(`room-${r}`).classList.toggle('active-room',r===n));nav.forEach(b=>b.classList.toggle('active',b.dataset.tab===n));if(n==='list')renderList()}
nav.forEach(b=>b.onclick=()=>room(b.dataset.tab));$('brand-button').onclick=()=>room('collection');
$('upload-button').onclick=()=>{if(!authUser){$('auth-dialog').showModal();toast('Enter your vault before uploading.');return}$('upload-dialog').showModal()};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
function profile(){ $('profile-title').textContent=authUser?(authUser.email?.split('@')[0]||'VAULT OWNER'):'PRIVATE SESSION';$('profile-status').textContent=authUser?'Private vault connected. Your signals and cover art belong to this session.':'Sign in to unlock your private vault and uploads.';$('auth-open').classList.toggle('hidden',!!authUser);$('sign-out').classList.toggle('hidden',!authUser) }
async function session(){if(!supabase)return;const{data}=await supabase.auth.getSession();authUser=data.session?.user||null;profile()}
$('auth-open').onclick=()=> $('auth-dialog').showModal();$('sign-out').onclick=async()=>{await supabase?.auth.signOut();authUser=null;renderEmpty();profile();toast('Vault session closed.')};
$('auth-form').onsubmit=async e=>{e.preventDefault();const email=$('auth-email').value.trim(),password=$('auth-password').value;if(!supabase)return;$('auth-message').textContent='AUTHENTICATING...';const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error){$('auth-message').textContent=error.message;return}authUser=data.user;$('auth-dialog').close();profile();await load();toast('Vault unlocked.')};
$('auth-signup').onclick=async()=>{const email=$('auth-email').value.trim(),password=$('auth-password').value;if(!supabase)return;if(password.length<6){$('auth-message').textContent='Password must be at least 6 characters.';return}$('auth-message').textContent='CREATING VAULT...';const{data,error}=await supabase.auth.signUp({email,password});if(error){$('auth-message').textContent=error.message;return}if(data.session){authUser=data.user;$('auth-dialog').close();profile();await load();toast('Vault created.')}else $('auth-message').textContent='Check your email to confirm the vault.'};
async function load(){if(!supabase||!authUser){renderEmpty();return}const{data,error}=await supabase.from('tracks').select('*').order('created_at',{ascending:true});if(error){renderEmpty();toast('Could not read the vault.');return}playlist=data||[];currentIndex=Math.min(currentIndex,Math.max(0,playlist.length-1));playlist.length?select(false):renderEmpty()}
function renderEmpty(){playlist=[];$('current-album-art').src='assets/default-art.jpg';$('player-thumb').src='assets/default-art.jpg';$('hero-title').textContent='VAULT EMPTY';$('hero-artist').textContent='UPLOAD A SIGNAL';$('player-title').textContent='VAULT EMPTY';$('player-artist').textContent='NO SIGNAL';$('player-status-label').textContent='STAND BY';$('list-count').textContent='0 SIGNALS';wheel.innerHTML='<div class="song-item active"><strong>VAULT EMPTY</strong><small>UPLOAD YOUR FIRST SIGNAL</small></div>'}
function select(auto){const s=playlist[currentIndex];if(!s)return renderEmpty();const art=cover(s);$('current-album-art').src=art;$('player-thumb').src=art;$('hero-title').textContent=s.title||'UNTITLED';$('hero-artist').textContent=s.artist||'UNKNOWN ARTIST';$('player-title').textContent=s.title||'UNTITLED';$('player-artist').textContent=s.artist||'UNKNOWN ARTIST';player.load({audioUrl:audio(s)});analyzer.init();analyzer.resume();renderWheel();if(auto)player.play()}
function renderWheel(){wheel.innerHTML='';playlist.forEach((s,i)=>{const d=i-currentIndex,b=document.createElement('button');b.className=`song-item ${i===currentIndex?'active':''}`;b.style.opacity=Math.max(.12,1-Math.abs(d)*.17);b.style.transform=`translateX(${Math.min(30,Math.abs(d)*4)}px) scale(${Math.max(.72,1-Math.abs(d)*.045)})`;b.innerHTML=`<strong>${esc(s.title||'Untitled')}</strong><small>${esc(s.artist||'Unknown Artist')}</small>`;b.onclick=()=>{currentIndex=i;select(true)};wheel.appendChild(b)})}
function move(dir,auto=true){if(!playlist.length)return;currentIndex=shuffle?Math.floor(Math.random()*playlist.length):(currentIndex+dir+playlist.length)%playlist.length;select(auto)}
selector.onwheel=e=>{e.preventDefault();move(e.deltaY>0?1:-1,false)};let touchY=0;selector.onpointerdown=e=>touchY=e.clientY;selector.onpointerup=e=>{const d=touchY-e.clientY;if(Math.abs(d)>22)move(d>0?1:-1,true)};
$('play-pause-btn').onclick=()=>{if(!playlist.length)return;analyzer.init();analyzer.resume();player.togglePlay()};$('next-btn').onclick=()=>move(1,true);$('prev-btn').onclick=()=>move(-1,true);$('shuffle-btn').onclick=()=>{shuffle=!shuffle;$('shuffle-btn').classList.toggle('active',shuffle);toast(shuffle?'SHUFFLE ACTIVE':'SHUFFLE OFF')};player.onEnded=()=>move(1,true);
player.onPlayStateChange=p=>{$('play-icon').textContent=p?'Ⅱ':'▶';$('player-status-label').textContent=p?'SIGNAL ACTIVE':'PAUSED';$('player-status-label').previousElementSibling?.classList.toggle('live',p)};player.onTimeUpdate=(t,d)=>{$('current-time').textContent=fmt(t);$('total-time').textContent=fmt(d);$('wave-progress').style.left=`${d?t/d*100:0}%`};$('waveform-container').onclick=e=>{if(!player.duration)return;const r=e.currentTarget.getBoundingClientRect();player.seek((e.clientX-r.left)/r.width*player.duration)};
function renderList(){$('list-count').textContent=`${playlist.length} SIGNALS`;$('list-container').innerHTML=playlist.length?playlist.map((s,i)=>`<button class="list-row ${i===currentIndex?'current':''}" data-i="${i}"><img src="${esc(cover(s))}" alt=""><div><strong>${esc(s.title||'Untitled')}</strong><small>${esc(s.artist||'Unknown Artist')}</small></div><em>${esc(s.album||'VAULT SIGNAL')}</em></button>`).join(''):'<div class="profile-status">No signals in the vault.</div>';document.querySelectorAll('.list-row').forEach(r=>r.onclick=()=>{currentIndex=+r.dataset.i;select(true);room('collection')})}
const eq=[...document.querySelectorAll('.eq-bands input')];function eqDraw(){const v=eq.map(i=>+i.value);$('eq-status').textContent=v.every(x=>x===0)?'FLAT':`${v.filter(x=>x!==0).length} BANDS ACTIVE`};eq.forEach(i=>i.oninput=eqDraw);$('eq-reset').onclick=()=>{eq.forEach(i=>i.value=0);eqDraw()};eqDraw();
function wave(){const c=$('waveform-canvas'),x=c.getContext('2d'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,r.width,r.height);const data=analyzer.getWaveformData();x.beginPath();for(let px=0;px<r.width;px++){const i=data.length?Math.floor(px/r.width*data.length):0,y=r.height/2+(data.length?(data[i]-128)/128:0)*r.height*.38;px?x.lineTo(px,y):x.moveTo(px,y)}x.strokeStyle='rgba(255,255,255,.72)';x.stroke();requestAnimationFrame(wave)}wave();
function fname(id,input){$(input).onchange=()=>$(id).textContent=$(input).files[0]?.name||'Choose a file'}fname('audio-file-name','audio-file');fname('cover-file-name','cover-file');
$('upload-form').onsubmit=async e=>{e.preventDefault();if(!authUser)return;const f=new FormData(e.currentTarget),a=f.get('audio'),c=f.get('cover');if(!a?.size){$('upload-progress').textContent='Select an audio file.';return}$('submit-upload').disabled=true;$('upload-progress').textContent='UPLOADING SIGNAL...';try{const base=`${authUser.id}/${crypto.randomUUID()}`,ap=`${base}-${a.name.replace(/[^a-z0-9._-]/gi,'_')}`;let r=await supabase.storage.from('audio').upload(ap,a,{contentType:a.type||'audio/mpeg'});if(r.error)throw r.error;let cp=null;if(c?.size){cp=`${base}-${c.name.replace(/[^a-z0-9._-]/gi,'_')}`;r=await supabase.storage.from('covers').upload(cp,c,{contentType:c.type||'image/jpeg'});if(r.error)throw r.error}const{error}=await supabase.from('tracks').insert({user_id:authUser.id,title:f.get('title'),artist:f.get('artist'),album:f.get('album')||null,genre:f.get('genre')||null,audio_path:ap,cover_path:cp});if(error)throw error;$('upload-dialog').close();e.currentTarget.reset();$('audio-file-name').textContent='Choose an audio file';$('cover-file-name').textContent='Optional cover image';await load();toast('Signal added to the vault.')}catch(err){$('upload-progress').textContent=err.message||'Upload failed.'}finally{$('submit-upload').disabled=false}};
session().then(load);
