/* Frequency — real Supabase-backed client. Replace these two values before use. */
const SUPABASE_URL = 'YOUR_SUPABASE_URL';
const SUPABASE_ANON_KEY = 'YOUR_SUPABASE_PUBLISHABLE_KEY';
const configured = !SUPABASE_URL.startsWith('YOUR_') && !SUPABASE_ANON_KEY.startsWith('YOUR_');
const sb = configured ? supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;

const $ = s => document.querySelector(s);
const audio = $('#audio');
let tracks = [], playlists = [], currentIndex = -1, shuffle = false, repeat = false, authMode = 'signin', viewMode = localStorage.getItem('frequency-view') || 'collection', dragStartX = null, dragMoved = false;

function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(sec){if(!Number.isFinite(sec))return '0:00';sec=Math.floor(sec);return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
async function signed(bucket,path){if(!path)return null;if(!configured)return null;const {data,error}=await sb.storage.from(bucket).createSignedUrl(path,3600);if(error){console.error(error);return null}return data?.signedUrl||null}
async function coverFor(t){return await signed('covers',t.cover_path)}
function placeholder(label){return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><rect width="600" height="600" fill="#15171c"/><circle cx="300" cy="300" r="220" fill="none" stroke="#343842"/><text x="50%" y="52%" text-anchor="middle" fill="#f2f3f5" font-family="Arial" font-size="90" font-weight="700">${escapeHtml((label||'F')[0]).toUpperCase()}</text></svg>`)}`}

function setAuthVisible(logged){$('#authView').classList.toggle('hidden',logged);$('#appView').classList.toggle('hidden',!logged)}
function authMessage(msg=''){ $('#authStatus').textContent=msg }

async function boot(){
  if(!configured){setAuthVisible(true);$('#authSubmit').disabled=true;authMessage('Connect Supabase in app.js to enable real accounts and storage.');return}
  const {data:{session}}=await sb.auth.getSession();setAuthVisible(!!session);if(session)await loadAll();
  sb.auth.onAuthStateChange(async(_event,session)=>{setAuthVisible(!!session);if(session)await loadAll()});
}

$('#authToggle').onclick=()=>{authMode=authMode==='signin'?'signup':'signin';$('#authSubmit').textContent=authMode==='signin'?'Sign in':'Create account';$('#authToggle').textContent=authMode==='signin'?'Need an account? Sign up':'Already have an account? Sign in';authMessage('')}
$('#authForm').onsubmit=async e=>{e.preventDefault();if(!sb)return;const email=$('#authEmail').value.trim(),password=$('#authPassword').value;authMessage('Working…');let r=authMode==='signin'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});if(r.error)authMessage(r.error.message);else authMessage(authMode==='signup'?'Account created. Check your email if confirmation is enabled.':'Signed in.')}
$('#signOutBtn').onclick=async()=>{if(sb)await sb.auth.signOut()}

async function loadAll(){
  const [tr,pl]=await Promise.all([sb.from('tracks').select('*').order('created_at',{ascending:false}),sb.from('playlists').select('*').order('created_at',{ascending:false})]);
  if(tr.error){toast(tr.error.message);return} if(pl.error){toast(pl.error.message);return} tracks=tr.data||[];playlists=pl.data||[];renderAll();
}
function renderAll(){
  $('#trackCount').textContent=`${tracks.length} track${tracks.length===1?'':'s'}`;$('#emptyLibrary').classList.toggle('hidden',tracks.length>0);$('#collectionView').classList.toggle('hidden',tracks.length===0||viewMode!=='collection');$('#listView').classList.toggle('hidden',tracks.length===0||viewMode!=='list');
  $('#viewCollection').classList.toggle('active',viewMode==='collection');$('#viewList').classList.toggle('active',viewMode==='list');renderCarousel();renderList(tracks,$('#listView'));renderAlbums();renderPlaylists();
}
async function renderCarousel(){const c=$('#carousel');c.innerHTML='';if(!tracks.length)return;const center=currentIndex>=0?currentIndex:0;const visible=Math.min(tracks.length,7);const half=Math.floor(visible/2);for(let offset=-half;offset<=half;offset++){let idx=(center+offset+tracks.length)%tracks.length,t=tracks[idx];let el=document.createElement('button');el.className='carousel-card '+(offset===0?'active':'');el.dataset.index=idx;let img=document.createElement('img');img.src=await coverFor(t)||placeholder(t.title);el.appendChild(img);let x=offset*235,y=Math.abs(offset)*18,z=10-Math.abs(offset);el.style.transform=`translateX(${x}px) translateY(${y}px) scale(${offset===0?1:.78-Math.abs(offset)*.04})`;el.style.zIndex=z;el.style.opacity=offset===0?1:Math.max(.22,1-Math.abs(offset)*.18);el.style.filter=offset===0?'none':'brightness(.65)';el.onclick=()=>{if(!dragMoved){currentIndex=idx;renderCarousel();playTrack(idx)}};c.appendChild(el)}}
function renderList(items,target){target.innerHTML=items.length?items.map((t,i)=>`<div class="track-row"><img class="track-art" data-cover="${escapeHtml(t.id)}" src="${placeholder(t.title)}"><div class="track-info"><strong>${escapeHtml(t.title)}</strong><span>${escapeHtml(t.artist)}${t.album?' · '+escapeHtml(t.album):''}</span></div><div class="row-actions"><button class="small-btn" data-play="${escapeHtml(t.id)}">Play</button></div></div>`).join(''):`<p class="muted">No results.</p>`;target.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{const i=tracks.findIndex(t=>t.id===b.dataset.play);if(i>=0){currentIndex=i;renderCarousel();playTrack(i)}});target.querySelectorAll('[data-cover]').forEach(async img=>{const t=tracks.find(x=>x.id===img.dataset.cover);const u=await coverFor(t);if(u)img.src=u})}
async function renderAlbums(){const g=$('#albumsGrid'),map=new Map();tracks.forEach(t=>{const key=t.album||'Singles';if(!map.has(key))map.set(key,t)});g.innerHTML=[...map.entries()].map(([name,t])=>`<div class="grid-card"><img class="grid-art" data-album-cover="${escapeHtml(t.id)}" src="${placeholder(name)}"><strong>${escapeHtml(name)}</strong><span>${escapeHtml(t.artist)}</span></div>`).join('')||'<p class="muted">Albums will appear here after you upload music.</p>';g.querySelectorAll('[data-album-cover]').forEach(async img=>{const t=tracks.find(x=>x.id===img.dataset.albumCover);const u=await coverFor(t);if(u)img.src=u})}
async function renderPlaylists(){const g=$('#playlistsGrid');g.innerHTML=playlists.map(p=>`<div class="grid-card"><img class="grid-art" data-pl-cover="${escapeHtml(p.id)}" src="${placeholder(p.name)}"><strong>${escapeHtml(p.name)}</strong><span>${escapeHtml(p.description||'Playlist')}</span></div>`).join('')||'<p class="muted">No playlists yet.</p>';g.querySelectorAll('[data-pl-cover]').forEach(async img=>{const p=playlists.find(x=>x.id===img.dataset.plCover);const u=await signed('covers',p.cover_path);if(u)img.src=u})}

async function playTrack(index){if(!tracks[index])return;currentIndex=index;const t=tracks[index];const url=await signed('audio',t.audio_path);if(!url){toast('Could not access this audio file.');return}audio.src=url;audio.currentTime=0;audio.play().catch(()=>{});$('#playerTitle').textContent=t.title;$('#playerArtist').textContent=t.artist;const u=await coverFor(t);$('#playerCover').style.backgroundImage=u?`url("${u}")`:'';$('#playerCover').style.backgroundSize='cover';$('#playerCover').textContent=u?'':'F';$('#playBtn').textContent='❚❚'}
function next(){if(!tracks.length)return;let i;if(shuffle)i=Math.floor(Math.random()*tracks.length);else i=(currentIndex+1)%tracks.length;if(!repeat&&currentIndex===tracks.length-1&&!shuffle){audio.pause();return}playTrack(i)}
function prev(){if(audio.currentTime>4){audio.currentTime=0;return}let i=(currentIndex-1+tracks.length)%tracks.length;playTrack(i)}
$('#playBtn').onclick=()=>{if(!audio.src&&tracks.length){playTrack(currentIndex>=0?currentIndex:0);return}audio.paused?audio.play():audio.pause()};$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;$('#shuffleBtn').onclick=()=>{shuffle=!shuffle;$('#shuffleBtn').classList.toggle('active',shuffle)};$('#repeatBtn').onclick=()=>{repeat=!repeat;$('#repeatBtn').classList.toggle('active',repeat)};audio.onplay=()=>$('#playBtn').textContent='❚❚';audio.onpause=()=>$('#playBtn').textContent='▶';audio.onended=next;audio.ontimeupdate=()=>{$('#currentTime').textContent=fmt(audio.currentTime);$('#progress').value=audio.duration?(audio.currentTime/audio.duration*100):0};audio.onloadedmetadata=()=>$('#duration').textContent=fmt(audio.duration);$('#progress').oninput=e=>{if(audio.duration)audio.currentTime=(+e.target.value/100)*audio.duration};$('#volume').oninput=e=>audio.volume=+e.target.value;audio.volume=.8;

function switchPage(page){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));$('#page-'+page).classList.add('active-page');$('#pageTitle').textContent=page[0].toUpperCase()+page.slice(1)}document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));
$('#viewCollection').onclick=()=>{viewMode='collection';localStorage.setItem('frequency-view',viewMode);renderAll()};$('#viewList').onclick=()=>{viewMode='list';localStorage.setItem('frequency-view',viewMode);renderAll()};$('#uploadBtn').onclick=$('#emptyUploadBtn').onclick=()=>$('#uploadModal').classList.remove('hidden');$('#newPlaylistBtn').onclick=()=>$('#playlistModal').classList.remove('hidden');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));

$('#carousel').addEventListener('pointerdown',e=>{dragStartX=e.clientX;dragMoved=false});$('#carousel').addEventListener('pointermove',e=>{if(dragStartX!==null&&Math.abs(e.clientX-dragStartX)>12)dragMoved=true});$('#carousel').addEventListener('pointerup',e=>{if(dragStartX===null)return;const dx=e.clientX-dragStartX;if(Math.abs(dx)>50){currentIndex=(currentIndex+(dx<0?1:-1)+tracks.length)%tracks.length;renderCarousel()}dragStartX=null;setTimeout(()=>dragMoved=false,80)});$('#carousel').addEventListener('wheel',e=>{if(!tracks.length)return;e.preventDefault();currentIndex=(currentIndex+(e.deltaY+e.deltaX>0?1:-1)+tracks.length)%tracks.length;renderCarousel()},{passive:false});

$('#searchInput').oninput=()=>{const q=$('#searchInput').value.toLowerCase().trim();renderList(tracks.filter(t=>`${t.title} ${t.artist} ${t.album||''} ${t.genre||''}`.toLowerCase().includes(q)),$('#searchResults'))};

$('#uploadForm').onsubmit=async e=>{e.preventDefault();if(!sb)return;const user=(await sb.auth.getUser()).data.user;if(!user)return;const audioFile=$('#trackFile').files[0],coverFile=$('#coverFile').files[0];$('#uploadStatus').textContent='Uploading…';try{const audioPath=`${user.id}/${crypto.randomUUID()}-${audioFile.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;let r=await sb.storage.from('audio').upload(audioPath,audioFile,{upsert:false});if(r.error)throw r.error;let coverPath=null;if(coverFile){coverPath=`${user.id}/${crypto.randomUUID()}-${coverFile.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;r=await sb.storage.from('covers').upload(coverPath,coverFile,{upsert:false});if(r.error)throw r.error}const meta={user_id:user.id,title:$('#trackTitle').value.trim(),artist:$('#trackArtist').value.trim(),album:$('#trackAlbum').value.trim()||null,genre:$('#trackGenre').value.trim()||null,year:$('#trackYear').value?Number($('#trackYear').value):null,duration:null,audio_path:audioPath,cover_path:coverPath};r=await sb.from('tracks').insert(meta);if(r.error)throw r.error;$('#uploadStatus').textContent='Uploaded.';e.target.reset();await loadAll();setTimeout(()=>$('#uploadModal').classList.add('hidden'),500)}catch(err){console.error(err);$('#uploadStatus').textContent=err.message||'Upload failed.'}}

$('#playlistForm').onsubmit=async e=>{e.preventDefault();if(!sb)return;const user=(await sb.auth.getUser()).data.user;if(!user)return;const file=$('#playlistCover').files[0];$('#playlistStatus').textContent='Creating…';try{let coverPath=null;if(file){coverPath=`${user.id}/playlist-${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const r=await sb.storage.from('covers').upload(coverPath,file);if(r.error)throw r.error}const r=await sb.from('playlists').insert({user_id:user.id,name:$('#playlistName').value.trim(),description:$('#playlistDescription').value.trim()||null,cover_path:coverPath});if(r.error)throw r.error;e.target.reset();$('#playlistStatus').textContent='Created.';await loadAll();setTimeout(()=>$('#playlistModal').classList.add('hidden'),500)}catch(err){$('#playlistStatus').textContent=err.message||'Could not create playlist.'}}

$('#playActive').onclick=()=>{if(currentIndex<0)currentIndex=0;playTrack(currentIndex)};
boot();
